### ISSUE TITLE
Remove EuclideanRing Unit instance

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript-prelude#102]
Apparently almost all texts regard the zero ring (i.e. the ring with a single element, which corresponds to our `Ring Unit` instance) as not being an integral domain: http://math.stackexchange.com/questions/1326505/is-the-zero-ring-a-domain, and for similar reasons it is generally agreed that there is no field with one element (see: https://en.wikipedia.org/wiki/Field_with_one_element).

The `EuclideanRing Unit` / `Field Unit` instances *do* satisfy all the laws we've specified for our type classes, though, AFAICT. So perhaps that means some laws need minor amendments to account for how `zero` behaves. I should be able to better say what that might be later in the semester once I know a bit more about rings and ideals and things. :)

**Comment by hdgarrood** [comment]
Here's a definition of integral domain which would outlaw our `EuclideanRing Unit` instance: https://ncatlab.org/nlab/show/integral+domain

**Comment by garyb** [comment]
Looks like there are a number of equivalent definitions, but the "no nonzero zero divisors" is probably the (subjectively) simplest one that reveals the problem with one-element rings, given that element is always zero in ring terms?

**Comment by garyb** [comment]
Either that, or something like "it has a nonzero multiplicative identity". Seems like the requirement of a multiplicative identity is not always followed, according to wikipedia.

**Comment by hdgarrood** [comment]
I like "has a nonzero multiplicative identity". I think that's probably best phrased as "one /= zero" in PureScript.

**Comment by paf31** [comment]
I like this summary from the ncatlab page:

> any product of (finitely many) nonzero elements of R R (which includes the empty product 1) must be nonzero

That seems like the sort of deduction we might rely upon in equational reasoning.

**Comment by hdgarrood** [comment]
Ah yes, agreed. Do you think "one /= zero" is logically equivalent to that?

**Comment by paf31** [comment]
Well it certainly implies one /= zero, but I'm not sure the other way is true.

**Comment by paf31** [comment]
I'm just saying that I'm fine with the law since it implies some sensible thing 😄

**Comment by hdgarrood** [comment]
Now that #107 is in, all we need to do is remove this instance the next time we do a major release.

**Comment by LiamGoodacre** [comment]
Completed in https://github.com/purescript/purescript-prelude/pull/120
