### ISSUE TITLE
Export law functions?

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript-prelude#110]
`quickcheck-laws` is really handy, but it's not usable in every situation. For example, I have a Polynomial type in [`polynomials`](https://github.com/hdgarrood/purescript-polynomials) which can only be given an `Arbitrary` instance if the type argument has `Eq`, `Semiring`, and `Arbitrary` instances. This means that I can't e.g. use `quickcheck-laws` to check the `Functor` laws with it, because that would require an `Arbitrary (Polynomial A)` instance, which in turn requires a `Semiring A` instance, which does not exist (`A` is defined in `quickcheck-laws`).

Also, I might want to use testing libraries other than quickcheck, e.g. strongcheck or jack.

I think we can make it easier to test that instances abide by the relevant laws with property tests in more scenarios by creating a few more modules in `Prelude`, perhaps one `.Laws` module accompanying each module which defines a type class. So for example `Data.Eq.Laws` could export `symmetric :: forall a. (Eq a) => a -> a -> Boolean` which would be nothing more than `\x y -> (x == y) == (y == x)`. We might then re-export all of these law functions from another module `Prelude.Laws` for convenience. All existing modules would be unaffected.

**Comment by paf31** [comment]
👍 Sounds good. I like the idea of putting these in separate modules too, since then even very basic dead code elimination can remove them if they're not used.

**Comment by hdgarrood** [comment]
Cool, I'll send a PR soon :) If this seems to work well, we might want to add a note to the library authoring guide in the docs repo that recommends exporting laws as functions like this from a `.Laws` module whenever you define a type class which has laws.

**Comment by JordanMartinez** [comment]
Should this issue be closed?

**Comment by hdgarrood** [comment]
I'm in favour of closing this: I think it's probably best not to include law functions in the Prelude, as I argued in https://github.com/purescript/purescript-prelude/pull/197.
