### ISSUE TITLE
Rename `id` to `identity`

### ISSUE THREAD

**Issue by garyb** [purescript/purescript-prelude#122]
For the next release!

**Comment by LiamGoodacre** [comment]
I'm not against, but what's the reason for change?

**Comment by michaelficarra** [comment]
@LiamGoodacre It's not uncommon to shadow `id` with a local "identifier" binding. In general, I prefer length of name to be proportional to size of scope. :+1:

**Comment by natefaubion** [comment]
Or another way to put it: I've wanted to shadow `id` more often than I've been relieved over the brevity of `Prelude.id`.

**Comment by garyb** [comment]
> Or another way to put it: I've wanted to shadow `id` more often than I've been relieved over the brevity of `Prelude.id`.

Yeah, that's exactly my thinking :)

**Comment by seagreen** [comment]
Elm does this too (as seen on [this summary page](https://hakonrossebo.github.io/functional-programming-babelfish/)) as well as Stephen Diehl's [Protolude](https://github.com/sdiehl/protolude), so PureScript will be in good company after the change.

**Comment by paf31** [comment]
We could add an alias now, and remove `id` later.

**Comment by hdgarrood** [comment]
Come to think of it, I'm not sure how we could do this in a backwards-compatible way, given that `id` is a member of the `Category` class.

**Comment by garyb** [comment]
Yeah, I think the idea was you could define `identity = id` and start updating / writing new code with `identity` at the use sites, and then break the classes later.

**Comment by MonoidMusician** [comment]
(Bump) Are we going to make this happen for 0.12?

**Comment by paf31** [comment]
We'll probably need a round of (small) library updates for 0.12, so we can consider changing it then. I wouldn't mind either way.
