### ISSUE TITLE
Re-add DivisionRing?

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript-prelude#128]
I am working on a quaternion library and I was wondering if it might make sense to add a `DivisionRing` type class again, as follows:

```purescript
class Ring a <= DivisionRing a where
  recip :: a -> a
```

with the law that `x * recip x = recip x * x = one` for all nonzero `x`. There's no requirement for the ring to be commutative, and so this would allow us to provide a `DivisionRing Quaternion` instance.

If we were going to do this, we should change `Field` so that `DivisionRing` is a subclass as well.

Now of course with any `EuclideanRing` you can simply write `one / x` for `recip x`. Also, admittedly, the only 'useful' instance I can think of is `Quaternion`; I did some googling and wasn't really able to find any other useful examples of non-commutative division rings. But I think it would be nice to have a way of asking for the multiplicative inverse of an element of an arbitrary division ring without requiring it to be commutative.

**Comment by paf31** [comment]
Do you remember why it was removed?

**Comment by garyb** [comment]
In the previous discussion you dropped it from the proposed hierarchy: https://github.com/purescript/purescript-prelude/issues/61#issuecomment-196014850 :wink:

**Comment by paf31** [comment]
From the previous issue for anyone wondering:

> `Quaternion` would be a `EuclideanDomain` but not a `CommutativeRing` in this setting, but we wouldn't capture the fact that it had multiplicative inverses. This suggests that it makes sense to keep `EuclideanDomain <= DivisionRing` and have `(CommutativeRing, DivisionRing) <= Field`. Then `Quaternion` would be a `DivisionRing` but not a `Field`.

I'd be fine with adding that class, with the additional law that `one / x = recip x` for any `Field`, since that's where `div` and `recip` join up.

**Comment by hdgarrood** [comment]
I'm not sure that that additional law would be necessary, I think it's implied by the existing `EuclideanRing` and `Field` laws.

**Comment by hdgarrood** [comment]
That is: let `x` be a nonzero value of some type `A` with a `Field` instance (under the proposed hierarchy). We have from the `Field` laws that ``one `mod` x = zero``, and so combining this with the `EuclideanRing` laws we see that if we define `q = one / x` then we have that `one = q * x`. Now, the `DivisionRing` law saying that `recip x * x = x * recip x = one` establishes that the nonzero values of the type `A` form a group under multiplication, and of course group inverses are unique, so we must have `q = one / x = recip x`.

**Comment by paf31** [comment]
Is there any reason to formulate `DivisionRing` in terms of reciprocals instead of division?

**Comment by paf31** [comment]
Also, if we have two division operations, is it going to be clear which one users should use when they want to work abstractly?

**Comment by hdgarrood** [comment]
How would you formulate `DivisionRing` in terms of division? With noncommutative rings you can have left and right division, ie `p * recip q` or `recip q * p`, which might have different results. I think it's a bit of a misnomer really but that is what it's called; in my mind it's a ring for which the nonzero elements form a group under multiplication, so this was the natural formulation.

**Comment by hdgarrood** [comment]
Come to think of it, if we were to add `DivisionRing` like this, then a `Field` is precisely a commutative division ring, so the `Field` class would arguably become redundant.

**Comment by hdgarrood** [comment]
In fact, if we did this, would it make sense to have:

```purescript
class (CommutativeRing a, DivisionRing a) <= Field a
instance field :: (DivisionRing a, CommutativeRing a) => Field a
```

so that people could still write functions with `Field` constraints for the sake of brevity and familiarity, but people wouldn't need to declare their own `Field` instances?

**Comment by garyb** [comment]
Unfortunately instances like that don't work, they overlap with everything as the `a` commits before the constraints are checked.

**Comment by hdgarrood** [comment]
Yes, my idea was that that instance should overlap with everything because nobody should be declaring `Field` instances themselves, rather declaring `DivisionRing` and `CommutativeRing` instances and letting the compiler figure out that it's a `Field`.

**Comment by garyb** [comment]
Oh, I see! That's an interesting way of doing it.

**Comment by hdgarrood** [comment]
Also I imagine the following might come in useful at some point in the discussion:

Suppose a type `A` has a valid `DivisionRing` instance. If it also has a `EuclideanRing` instance, this instance must be equivalent to the following to be law-abiding:

```purescript
instance EuclideanRing a where
  div a b = a * recip b
  -- actually any nonnegative integer constant works here,
  -- but let's just stick with 1.
  degree _ = 1
  mod _ _ = zero
```

**Proof.** This follows from the submultiplicativity law on the `EuclideanRing` class:

* For all nonzero `a` and `b`, we have `degree a <= degree (a * b)`

Suppose `a : A` and `a` is nonzero. Then, `degree (one : A) <= degree (one * a) = degree a`. Also, `degree a <= degree (a * recip a) = degree one`. So `degree a = degree one`, i.e. `degree` must be constant.

Since `degree` is constant, we cannot possibly have `degree r < degree b` for any `r, b : A`. Therefore, for any `a, b : A`, with `b` nonzero, the quotient/remainder law tells us that ``a `mod` b = zero``. Looking again at the same law and using this new fact, we have that `a = q * b` i.e. `a = (a / b) * b`. If we multiply both sides by `recip b` we see that `a * recip b = (a / b) * b * recip b = a / b`.

**Comment by hdgarrood** [comment]
> Also, if we have two division operations, is it going to be clear which one users should use when they want to work abstractly?

So coming back to this, I guess the division operations would be:

* `div :: EuclideanRing a => a -> a -> a`: requires commutativity, doesn't require nonzero elements to have multiplicative inverses
* `leftDiv, rightDiv :: DivisionRing a => a -> a -> a`, doesn't require commutativity, does require all nonzero elements to have a multiplicative inverse.

`leftDiv` would be defined as `leftDiv p q = recip q * p`, and `rightDiv` as `rightDiv p q = p * recip q`. These functions are probably not important enough to deserve an operator, I think.

Note that
* neither set is more general than the other
* if a type supports both sets then all the functions must be equivalent
* pretty much every useful `Ring` instance is commutative
* `Quaternion` is probably the only noncommutative division ring which might end up being used in PureScript code

Given all this, I'd say that it's not a problem that there is more than one division operator, and that people should always use `div` if they're working abstractly unless they know they want their code to work with `Quaternion` (or some other noncommutative `DivisionRing`).

In fact, it might even make sense not to provide `leftDiv` or `rightDiv` in terms of `DivisionRing` but instead continue providing specialised versions in the `quaternions` library. However I am leaning towards providing them, because they can be expressed using only operations from this proposed `DivisionRing` class, and the more general type signature gives you more information about what the function can (or rather can't) do.

aside: to make sure I have `leftDiv` and `rightDiv` the right way around I checked  [the documentation for `x \ y` in Octave](https://www.gnu.org/software/octave/doc/interpreter/Arithmetic-Ops.html#XREFldivide) and also [the Wikipedia page for "division"](https://en.wikipedia.org/wiki/Division_(mathematics)#Left_and_right_division). They're currently the wrong way around in my `quaternions` library, oops.

**Comment by paf31** [comment]
Can we construct any new interesting division rings from the quaternions? How about polynomials with quaternion coefficients? Is there such a thing as a free division ring? If Q is really the only example we have, then it might be better not to complicate things. I'm not sure.

Regarding naming, my only quibble is that `div` and `recip` seem like they should be interdefinable, so it seems a little odd to me that they belong in different hierarchies, but I guess there isn't much can be done about that if we want to support either but not the other.

**Comment by paf31** [comment]
The Wikipedia article also gives the rational quaternions and "skew Laurent series rings" as examples, although they are probably more esoteric than the regular quaternions.

**Comment by paf31** [comment]
[One more example here](https://math.stackexchange.com/a/542799).

Seems there are probably enough examples from abstract algebra to warrant a class.

**Comment by hdgarrood** [comment]
Right, yeah, also the endomorphism ring of a simple module is apparently also a division ring and in general noncommutative. I just don't imagine ever using any of these (although perhaps that's just a lack of imagination on my part).

We would have `div` and `recip` interdefinable if `div` were a member of `Field`; of course, the looser sense of division that `div` currently represents is more useful. In fact as an aside, having had a while to properly mull it over, I think you all did a really good job with how that part of the hierarchy is set up. :+1:
