### ISSUE TITLE
Adopt some of category sub classes

### ISSUE THREAD

**Issue by safareli** [purescript/purescript-prelude#133]
Recently I saw [this](https://youtu.be/vzLK_xE9Zy8) talk by @conal and there are some interesting aspects, like introducing `Cartasian` and `Closed` classes. 

With fandeps we can express Cartasian for example like this:
```purescript
class Category k => Cartasian k | k -> x where
  exl :: k (x a b) a
  exr :: k (x a b) b
  fork :: k a c -> k a d -> k a (x c d)
```

And possibly instead of `->` we can use this classes in prelude too. for example
```
f $ a :: (a -> b) -> a -> b
f $ a :: Closed k => ((a `k` b) `k` a) `k` b -- this might be incorrect
```

**Comment by paf31** [comment]
I would very much like to have a `purescript-categories` in the core library set, with, at a minimum, CCCs and symmetric and braided monoidal categories.

**Comment by paf31** [comment]
But I don't think it needs to be in Prelude.

**Comment by paf31** [comment]
> And possibly instead of -> we can use this classes in prelude too

I don't think we should do that, since we'd need to overload lambda for it to be really useful, but I think we could consider adding some sort of category notation.

**Comment by garyb** [comment]
Closing this as we're not going to do it in `Prelude` specifically.
