### ISSUE TITLE
Wrong signature for degree

### ISSUE THREAD

**Issue by jacereda** [purescript/purescript-prelude#139]
Looks like the `degree` signature is wrong:

https://github.com/purescript/purescript-prelude/blob/v3.1.0/src/Data/EuclideanRing.purs#L45

I added `quickcheck-laws` tests to `BigInt` and it fails in the `EuclideanRing` because of the `Int` return type.

I guess it should be returning an arbitrarily sized natural but we don't have those in prelude, right?

**Comment by hdgarrood** [comment]
In a perfect world it would return an arbitrarily sized natural number, but you're correct that we don't have those in Prelude. I think for now the best option is probably to write your own EuclideanRing tests for types where `degree` needs to be larger than `Int` allows.

**Comment by hdgarrood** [comment]
See also https://github.com/purescript/purescript-prelude/issues/99#issuecomment-275924909
