### ISSUE TITLE
Monomorphic and/or

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript-prelude#14]
`Lattice` does look really nice, but the absence of and / or functions specialized to `Boolean` does worry me a little. Given that it could make error messages harder to understand, and also given that Boolean and / or are arguably common enough that they deserve their own operators, would you consider specializing `(&&)` and `(||)` to `Boolean` values, and finding some other symbols for `sup` and `inf`?

**Comment by paf31** [comment]
I think that sounds like a good idea. I'm fine keeping `sup` and `inf` as the more generic names.

**Comment by garyb** [comment]
I don't think there are any monomorphic operators now, so why would `Boolean` be special in that?

I guess I don't mind though, we could use `\/` and `/\` for `sup` and `inf` operators, although this would unfortunately collide with the nested `Tuple` operator. I'd probably rather rename that though.

**Comment by hdgarrood** [comment]
True - in particular, given `(&&)` and `(||)` work for any `BoolLike` now, perhaps I'm imagining a problem that doesn't really exist. Have you ever encountered people confused by it? If not I suppose there isn't really sufficient evidence to justify action.

**Comment by hdgarrood** [comment]
Looks like it has confused at least one person before: http://ircbrowse.net/browse/purescript?events_page=103

**Comment by garyb** [comment]
That's down to `not` rather than the operators actually...

**Comment by garyb** [comment]
And really it's a problem because of not inferring constraints :wink:

**Comment by hdgarrood** [comment]
Ah, of course. Ok - never mind then.
