### ISSUE TITLE
Need more careful definition of a `DivisionRing` from a `Ring`

### ISSUE THREAD

**Issue by midfield** [purescript/purescript-prelude#144]
Adapted from a reddit conversation with paf31:

The way you define a `DivisionRing` from a `Ring` is

``` data Ratio a = Ratio a a
instance (Ring a) => DivisionRing (Ratio a) 
```

This is a problem because you're taking all pairs of elements from the original ring, e.g. you're allowing everything in the denominator.

The usual definition of localization of rings `R` with respect to a multiplicative system `S` (= things allowed in the denominator; needs to include the multiplicative unit and be closed under multiplication, so we can do addition) is: form a ring of pairs (ratios) with the equivalence relation `a1/b1 = a2/b2` if there exists a `t` in `S` so that `t(a1b2 - a2b1) = 0`; addition and multiplication follow the usual rules for fractions; the additive unit is `0/1` and the multiplicative unit is `1/1`. In particular `a/b = ax/b*x` for any `x` in `S`, so if `0` is in `S`, then everything is zero and you have the zero ring. More generally, if you have zero divisors in `S`, then the usual map `R -> R[S^-1]` is not injective.

Even if you don't want to use the usual equivalence relation, some of this weirdness is forced, just from the usual rules for adding and multiplying fractions. For example

```0/1*a/0 = 0/0```

which implies that `0/0` is the zero element (since `0*x = 0` in any ring.) So you need at least some kind of equivalence relation. But then

```a/b = 0/0 + a/b = (0b + a0)/(0*b) = 0/0```

so every element is zero.

Sorry this is kind of rambling, I'm also not remembering my algebra crisply.

**Comment by hdgarrood** [comment]
If anything I think this is a problem with the post http://blog.functorial.com/posts/2015-12-06-Counterexamples.html — I don’t think the issue you describe arises from any of the code in this repo. In particular we don’t define DivisionRing in terms of any Ratio type, we just say it’s a ring in which all nonzero elements have multiplicative inverses. The post presents ratios of elements from a ring as one way of constructing a division ring, but we haven’t mentioned that  here.

**Comment by midfield** [comment]
I agree, this came up during a conversation about said blog post.  I don't know anything about Purescript or the prelude (other than I want to try it out!)  Phil asked me to file this issue as a result of that conversation.

**Comment by paf31** [comment]
Thank you for writing this up. I wasn't sure if you were referring to an issue in DivisionRing itself, but in any case I can fix the post.

**Comment by hdgarrood** [comment]
I think I'll close this, since it didn't turn out to be a problem in this repo.
