### ISSUE TITLE
Data.Eq imports foreign `refIneq` but doesn't use it

### ISSUE THREAD

**Issue by metaleap** [purescript/purescript-prelude#147]
Would like to learn why? (Unless it's an oversight?) Instead of it, `notEq` essentially calls `eq(x, y) == false`.

I think most unsuspecting PureScripters targeting JS would like `/=` to turn into `!==` for the default instances. Not meant to bike-shed, just to understand!  =)

**Comment by garyb** [comment]
Ah, it can be removed actually - it's a leftover from when the `Eq` class used to require both `eq` and `notEq` to be defined by instances.

**Comment by metaleap** [comment]
Want a PR or already done?  😀

**Comment by garyb** [comment]
Sure, PR away :)

**Comment by hdgarrood** [comment]
This appears to have been resolved by #148.
