### ISSUE TITLE
Should `show (-0.0)` produce "-0.0"?

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript-prelude#152]
Currently, `show (-0.0) == "0.0"`, which is arguably wrong, since even though `-0` and `0` do compare equal, they produce different results when dividing by either of them.

**Comment by JamieBallingall** [comment]
I my view, yes, `show (-0.0)` should produce "-0.0".
As an external reference, Octave, which takes numbers seriously, shows `-0.0` as "-0".
I guess the only reason not to, at this stage, is if breaks too many things.

**Comment by kl0tl** [comment]
Should we also update the Eq instance for Number if we’re going to show -0.0 and 0.0 differently?

**Comment by hdgarrood** [comment]
For me personally, I think Number Eq being consistent with IEEE 754 (which does require 0 == -0) is more important than it satisfying x == y implies f x == f y

**Comment by hdgarrood** [comment]
Going to close this for now since it hasn’t had much interest, it’s a breaking change, and we are hoping to deprecate Show eventually anyway. See #236
