### ISSUE TITLE
Recommend extensional equality for `Eq` instances

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript-prelude#153]
While I think requiring an `Eq` instance to define an equivalence relation is definitely correct, I've felt for quite a long time that the bar for an `Eq` instance to be considered valid should actually be a little higher, based on e.g. the way `Eq` gets used generically. For example, currently, if we fix any nonzero `n :: Int`, the following would be a perfectly good `Eq Int` instance:

```purescript
instance Eq Int where
  eq = unsafeRefEq `on` (_ `rem` n)
```
(where `rem` is like `mod` except the result of ``x `rem` n`` is always between `0` and `n`, i.e. if the result is nonzero, then its sign matches the sign of the second argument.)

That would mean that the behaviour of of `nub [1,3,5,7,8,9]` (where `nub` is using the `Eq` constraint) could be any of `[1]`, `[1,8]`, `[1,3,5]`, `[1,3,8]`, `[1,3,5,7,8]`, or `[1,3,5,7,8,9]` for different choices of `n` above.

I think what I'm about to propose is a bit too hand-wavy to be described as a 'law', but it is a guideline I've been following for a while, and I think it makes a lot of sense and also matches up well with how `Eq` is actually used in practice. How do people feel about adding something like the following to the `Eq` docs:

> While not a strict requirement, when defining an `Eq` instance for some type `T`, it is recommended that for any pair of values `x :: T` and `y :: T`, the expression `x == y` should evaluate to `true` if and only if `x` and `y` are indistinguishable via the rest of the functions and instances which form the public API of `T`. In particular, if there is an (exported) function `f :: T -> U` for some other type `U` which itself has an `Eq` instance, then whenever `x == y` we should have `f x == f y` as well.
>
> This allows us to define `Eq` instances for data structures which hide their representation and may have more than one possible internal representation for a given value, such as `Map`, while still being sufficiently restrictive to ensure that `Eq` instances mostly act in an intuitive manner.

**Comment by garyb** [comment]
So `Eq` should also imply extensional equality, basically? :smile:

**Comment by hdgarrood** [comment]
Right, yeah. I think that's how `Eq` is actually used in practice.

**Comment by paf31** [comment]
I feel like this should be a subclass.

**Comment by hdgarrood** [comment]
I think I'd be happier leaving it the way it is than creating a subclass, actually; I think `Eq` is already well established in everyone's minds as the class which gives you equality, and so if we made a new subclass I'm not sure I can see it being used very much.

We do already describe `Eq` as being for types with "decidable equality"; that ought to at least imply what I'm suggesting, right? If `Eq` is truly just a class for equivalence relations, then surely it should be called `Equiv` or something instead, and the operator should be something like `~` rather than `==`?

**Comment by paf31** [comment]
I don't think decidable equality means that that equality is any particular sort of equality. It just means that it terminates on all inputs, regardless of whether things are equal or not (as opposed to semi-decidable equality, or decidable apartness).

To elaborate on what I said earlier, I think it's really useful to have `Eq` mean an equivalence relation, so that, for example, things like `sortBy` and `groupBy` can be used to group things into equivalence classes. Also, I'm used to "extensional equality" in the sense of set theory and also in the sense of dependent type theory, but I'm not sure what it means for us, and I think it might be hard to pin down a rigorous definition. I can write an `Eq` instance for `IO ()` for example, which always returns `true`, but I certainly can't give any sensible definition of observable equality for `IO ()`.

**Comment by paf31** [comment]
Actually, one way you could possibly make it rigorous is to talk about "equality in all contexts". Maybe something like `p(x) = p(y)` for all predicates `p` and `x == y`.

Even for `IO`, that's not going to work, so I think it makes a decent subclass, although maybe not one which would be used all that much, so maybe not a good candidate for Prelude.

**Comment by hdgarrood** [comment]
> I think it's really useful to have Eq mean an equivalence relation, so that, for example, things like sortBy and groupBy can be used to group things into equivalence classes

Grouping things into equivalence classes is certainly useful, but `sortBy` and `groupBy` don't use `Eq`, they use a function of type `a -> a -> Boolean`. In fact I think a function `a -> a -> Boolean`, or possibly `Eq b => a -> b` (where the type `b` represents some indexing set for the set of equivalence classes) is probably a better way of encoding some equivalence relation than a type class, because I don't think many types have just one obvious equivalence relation, and also every type has the trivial equivalence relation `const (const true)`.

Do we want to give `Eff` an `Eq` instance which always returns `true`? We don't have that instance currently and I'm not sure I'd be in favour of adding it. To me, this is a feature of the above recommendation, not a drawback.

**Comment by hdgarrood** [comment]
Oh actually, `sortBy` is `a -> a -> Ordering` of course; it needs an ordering rather than an equivalence relation.

**Comment by garyb** [comment]
Discussed a bit further here: https://www.reddit.com/r/haskell/comments/87mf4v/is_it_considered_acceptable_for_eq_instances_to/
