### ISSUE TITLE
Data.Function.iterate

### ISSUE THREAD

**Issue by matthewleon** [purescript/purescript-prelude#155]
Not sure about the name, but something like `(a -> a) -> Int -> a -> a`. I searched all over pursuit and core for this, and don't see it anywhere.

**Comment by garyb** [comment]
Like a `replicate` / `replicateA` kind of thing?

**Comment by matthewleon** [comment]
Like `replicate`, but without materializing a container. In Haskell, you could just use a `replicate` function with `last`, because of Laziness. Not so simple in PS, right?

**Comment by matthewleon** [comment]
(Actually, not sure how much the approach I just brought up helps in Haskell... Anyway, that's beside the point, I think.)

**Comment by LiamGoodacre** [comment]
Generalise to ~`Semigroupoid`~ `Category`?

**Comment by hdgarrood** [comment]
I think this is `power` with the `Endo` monoid: https://pursuit.purescript.org/packages/purescript-monoid/3.3.0/docs/Data.Monoid#v:power

**Comment by matthewleon** [comment]
> I think this is power with the Endo monoid

1) That is indeed true, thanks.

2) But not stack-safe.

3) And also really not obvious to people looking to iterate a function `n` times.

I'll take a look at 2)... Maybe there is a simple trick. But that's a separate issue.

As for 3), I do think this is something a fair number of people want to do, and could be exposed in `Data.Function`.

Examples:
https://stackoverflow.com/questions/7423123/how-to-call-the-same-function-n-times
https://stackoverflow.com/questions/3911060/library-function-to-compose-a-function-with-itself-n-times

**Comment by matthewleon** [comment]
I think maybe @LiamGoodacre 's suggestion of generalizing to `Category` could maybe be done with stack safety? I'll give it a shot...

**Comment by matthewleon** [comment]
Ac

**Comment by matthewleon** [comment]
Actually, I'm being stupid here. The issue is that any general approach will create a huge recursive thunk at the end. I don't really see any way to do this stack safely with any level of generality.

What do people think?

**Comment by hdgarrood** [comment]
Yeah, that seems to me to be a sufficiently good reason to have the concrete version. I’ve defined this locally in a project before as it happens; I called it `applyN`, but `iterate` seems like an equally good name for it.

**Comment by matthewleon** [comment]
I actually kind of prefer `applyN`, because Haskell defines `iterate` to produce a `List`. I'll make a quick PR.

**Comment by garyb** [comment]
Resolved by #156
