### ISSUE TITLE
Applicative.noop

### ISSUE THREAD

**Issue by matthewleon** [purescript/purescript-prelude#160]
It might be a nice convenience to provide `noop = pure unit`. I feel like I see `pure unit` often enough that it would be sensible to have a community-adopted shorthand for it.

**Comment by hdgarrood** [comment]
I’m not a huge fan personally; it’s not as if `pure unit` is particularly burdensome to type out, and it would be one more thing you have to learn if you’re starting out.

**Comment by matthewleon** [comment]
> it’s not as if pure unit is particularly burdensome to type out, and it would be one more thing you have to learn if you’re starting out.

I think many people probably feel this way as well. I'll close this (and other such shorthand Issues for very simple compositions).

**Comment by garyb** [comment]
Related: https://mail.haskell.org/pipermail/libraries/2012-February/017548.html
