### ISSUE TITLE
Add `Monoid` to prelude?

### ISSUE THREAD

**Issue by garyb** [purescript/purescript-prelude#163]
Perhaps we should just deprecate the library and roll it into `Prelude`, since `Monoid` is super common?

I'd also be in favour of adding @matthewleon's `Semigroup` newtypes in then too, as it seems sensible to follow the same pattern we use for monoids, assuming we do move those over at the same time.

/cc @paf31 (if you're interested at all), @kRITZCREEK, @LiamGoodacre + anyone else with thoughts on it

**Comment by gabejohnson** [comment]
I agree with moving the class, but are the `Monoid` newtypes used frequently enough to warrant inclusion in the Prelude?

**Comment by garyb** [comment]
They're used to implement a good chunk of the functions in `foldable-traversable` but I guess they could remain in a library. Aside from `Alternative` they're all monoidifications of classes in `Prelude` though, so it doesn't seem unreasonable to have them here too 🤷‍♂️.

**Comment by LiamGoodacre** [comment]
Sounds good to me.  Also mirrors that we have Semigroupoid and Category both in Prelude.
