### ISSUE TITLE
Enable Ord Record instance and clarify its equivalence to compiler derived Ord

### ISSUE THREAD

**Issue by natefaubion** [purescript/purescript-prelude#176]
Compiler derived Ord for records is the same as RowToList ordering. I'd suggest we enable it (it's currently commented out) and note the equivalence between:

```
newtype MyRecord = MyRecord {...}
```
```
derive instance ordMyRecord :: Ord MyRecord
```
```
instance ordMyRecord :: Ord MyRecord where
  compare (MyRecord r1) (MyRecord r2) = compare r1 r2
```

**Comment by garyb** [comment]
I’d also be fine with this - I wasn’t really sure why the alphabetical label ordering was thought to be a problem, given that’s how derived instances work, and how generics did.

It needs documenting somewhere of course, but I don’t think it’s particularly strange - it seems “obvious“  that there would need to be some canonical ordering, given record labels are a set.
