### ISSUE TITLE
Lost functionality after merging old monoid library

### ISSUE THREAD

**Issue by Thimoteus** [purescript/purescript-prelude#179]
Taking `Conj` as an example, the old version has [several instances](https://pursuit.purescript.org/packages/purescript-monoid/3.3.0/docs/Data.Monoid.Conj#t:Conj) which cannot be used for the newtypes here, since the classes are defined downstream. In particular, it's not possible to do `Data.Newtype.ala Conj foldMap`, though you can recover the same idea using [`Data.Lens.Iso.au`](https://pursuit.purescript.org/packages/purescript-profunctor-lenses/4.0.0/docs/Data.Lens.Iso#v:au). In addition, the `Alternate` newtype has been lost completely.

**Comment by LiamGoodacre** [comment]
@garyb - I remember us talking about moving `Alternate` somewhere, but not sure where.

**Comment by garyb** [comment]
@Thimoteus I don't think we've lost anything, the `Newtype` instances are still defined, just with the class instead: https://github.com/purescript/purescript-newtype/blob/master/src/Data/Newtype.purs#L48

@LiamGoodacre yeah, there's a PR for that now too 🙂 purescript/purescript-control#50

**Comment by Thimoteus** [comment]
Ahh! Neat.

**Comment by Thimoteus** [comment]
With [this PR](https://github.com/purescript/purescript-invariant/pull/8/files) I think all that's missing is the `Invariant` instance for `Alternate`. However, in the partial ordering of dependencies, `purescript-invariant` and `purescript-control` are incomparable.

**Comment by hdgarrood** [comment]
I think having either of `invariant` or `control` depend on the other ought to be fine; at the moment, both only depend on Prelude. Perhaps having `invariant` depend on `control` would be better since I expect the latter is more commonly used.

**Comment by hdgarrood** [comment]
Closing in favour of https://github.com/purescript/purescript-invariant/issues/9
