### ISSUE TITLE
travis: script could be written to not require `sudo`

### ISSUE THREAD

**Issue by matthewleon** [purescript/purescript-prelude#182]
The Travis script for this, and other core PS libraries, could probably be written so as to not include `sudo: required`, no? According to their docs, this causes the builds to run in a containerized environment, which has the benefit of being faster: https://docs.travis-ci.com/user/reference/overview/

**Comment by garyb** [comment]
Probably yeah. They're using `sudo: required` as that's required for `dist: trusty`. And that was required as the prior containers behaved awfully (would hang and time out more often than not) unless you set the compiler thread count to 1 in the RTS settings, and even then it was abnormally slow. :smile:

I think someone tried out a newer container distro a while ago on some repo and it seemed okay though, we've just not changed it again as the startup delay hasn't been painful enough to motivate faffing around with Travis again.
