### ISSUE TITLE
left-associative `apply` operator

### ISSUE THREAD

**Issue by acple** [purescript/purescript-prelude#185]
The `apply` is known as operator `$` that is right-associative.
I am now learning F#, has the 'backward-pipe operator' `<|` with type `(a -> b) -> a -> b` is left-associative.
It is very useful in several scenes.

```PureScript
module Data.Function where
...

infixr 0 apply as $
infixl 1 apply as |$ -- left-associative version, need to consider which symbol use
```

```PureScript
let x = f |$ g a b |$ h c |$ d

-- is equivalent to:
let x = f (g a b) (h c) d

\_ -> myfunc
  |$ parameter aaaa
  |$ expression <$> is
  |$ verylong
```

This is more clear for multi param function application, in limited usecases.

How do you think so?

**Comment by kedashoe** [comment]
like https://pursuit.purescript.org/packages/purescript-prelude/4.1.0/docs/Data.Function#v:(#) ?

**Comment by natefaubion** [comment]
(#) is left associative but the arguments are flipped. A left associative version of `$` lets you group arguments with a single delimiter. That is `foo |$ a + 1 |$ b + 2 |$ c + 3` is equivalent to `foo (a + 1) (b + 2) (c + 3)`.

**Comment by acple** [comment]
these are three apply operators difference:

```PureScript
f a $ g b $ h c === f a (g b (h c)) -- f :: a -> gbhc -> x

f a # g b # h c === h c (g b (f a)) -- f :: a -> y

f a |$ g b |$ h c === (f a) (g b) (h c) -- f :: a -> gb -> hc -> z
```

The third is now don't exist but i occasionally want it!

**Comment by acple** [comment]
Closing this, see #193.
