### ISSUE TITLE
Power for Semiring

### ISSUE THREAD

**Issue by JamieBallingall** [purescript/purescript-prelude#200]
Data.Monoid contains a function  [`power`](https://pursuit.purescript.org/packages/purescript-monoid/3.3.0/docs/Data.Monoid#v:power) which provides exponentiation by squaring.

A Semiring creates a Monoid under multiplication. Should there be an implementation of `power` for semirings? Something like:
`power :: forall m. Semiring a => a -> Int -> a`

An alternative would be to create seperate Monoid, AdditiveMonoid and MutliplicativeMonoid classes but that has been considered and rejected in #87.

I'm happy to create a PR for this but wanted to canvas views first because it seems a little repetitive.

**Comment by hdgarrood** [comment]
The intention is that you can use the [`Multiplicative`](https://pursuit.purescript.org/packages/purescript-prelude/4.1.0/docs/Data.Monoid.Multiplicative#t:Multiplicative) newtype for this:

```purescript
power :: forall a. Semiring a => a -> Int -> a
power x n = un Multiplicative (Monoid.power (Multiplicative x) n)
```

although perhaps this function is useful enough that it's worth providing.

**Comment by JamieBallingall** [comment]
I see. Or at least I think I see.
I'll close this and reopen if I am possessed of a stronger opinion on the topic.
Thanks!
