### ISSUE TITLE
Precision loss for 32-bit integer multiplication

### ISSUE THREAD

**Issue by iamahuman** [purescript/purescript-prelude#201]
https://github.com/purescript/purescript-prelude/blob/a96663b34364fdd0885a200955e35b99f4e58c43/src/Data/Semiring.js#L10-L15

I can't believe this was never mentioned as an issue before.

Maybe replace this with [Math.imul](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/imul)?

**Comment by garyb** [comment]
purescript/purescript#2980

**Comment by iamahuman** [comment]
My bad.

Closing as duplicate (but I think it might have fit here more...)

**Comment by garyb** [comment]
No worries, it's split between both! 🙂 

The numeric operations are inlined by the compiler where it can (kinda, the compiler produces code equivalent to their implementation here, it doesn't technically inline since it doesn't look at the JS implementation of them).
