### ISSUE TITLE
Add Show1 for unary type constructors

### ISSUE THREAD

**Issue by sedram** [purescript/purescript-prelude#205]
By analogy to Eq1. Haskell already has this [in Data.Functor.Classes](http://hackage.haskell.org/package/base-4.12.0.0/docs/src/Data.Functor.Classes.html#line-213). 

The question might be whether it matters if `showArray` is rewritten to use Show1.

I'd be happy to try making the pull request if this sounds reasonable.

**Comment by garyb** [comment]
Generally the need for `Show1` can be avoided by using something like [`TacitString`](https://github.com/slamdata/purescript-fixed-points/blob/master/src/Data/TacitString.purs): https://github.com/slamdata/purescript-fixed-points/blob/44ae7a7135bd17dc6d865d31f166a8cf5fa65c7e/src/Data/Functor/Mu.purs#L52-L53

**Comment by JordanMartinez** [comment]
I'm against this. I'd rather we implement the `Debug` class that Harry describes in this blog post: https://harry.garrood.me/blog/down-with-show-part-1/

**Comment by hdgarrood** [comment]
Yeah, also I think this has had little enough interest that we can justify closing (at least for now).
