### ISSUE TITLE
Add `Data.Monoid.replicate`

### ISSUE THREAD

**Issue by natefaubion** [purescript/purescript-prelude#221]
I've wanted this on several occasions and I think it would be a nice complement to `power`.

**Comment by hdgarrood** [comment]
Like this?
```
replicate :: forall f a. Applicative f => Semigroup (f a) => Int-> a -> f a
replicate n x = power n (pure x)
```

**Comment by natefaubion** [comment]
Something like:
```purescript
replicate :: forall m. Monoid m => m -> Int -> m
replicate val = go mempty 0 <<< max 0
  where
  go acc total n
    | total == n = acc
    | total == 0 = go val 1 n
    | total * 2 > n = acc <> go mempty 0 (n - total)
    | otherwise = go (acc <> acc) (total * 2) n
```

**Comment by hdgarrood** [comment]
I’m not sure I see the difference. Is the idea that it has the same result but different performance characteristics?

**Comment by natefaubion** [comment]
Oh I guess I just misunderstood the description of `power`. I assumed that for example `power 10 "a"` would result in 2^10 "a"s being printed, but it prints 10 "a"s.
