### ISSUE TITLE
Improve flip example in docs

### ISSUE THREAD

**Issue by milesfrain** [purescript/purescript-prelude#237]
The existing example for [`flip`](https://pursuit.purescript.org/packages/purescript-prelude/4.1.1/docs/Data.Function#v:flip) with `const` can be pretty confusing for beginners. See https://github.com/purescript-contrib/purescript-book/issues/260

Let's use a clearer example, like `div` or `sub`.

**Comment by natefaubion** [comment]
There is probably a better example than `const`, but the reason I think it's used, and something that I think is really important, is that it's easy to see by the types what is happening.
```
const :: forall a b. a -> b -> a
flip const :: forall a b. b -> a -> a
```
Whereas, something like `sub` might be
```
sub :: Int -> Int -> Int
flip sub :: Int -> Int -> Int
```

**Comment by milesfrain** [comment]
Then the existing example with `const` should probably be modified to use different types to showcase this feature.

I also think we should include a `sub`/`div` example too.

Any objections to multiple examples?

**Comment by hdgarrood** [comment]
I think multiple examples is fine as long as it doesn’t make the docs too long. Adding a sentence to say something like “flip is useful when you want to partially apply arguments in a different order to the order expected by the function you’re using” would probably be good too.
