### ISSUE TITLE
[generics-rep] No instance for Unit?

### ISSUE THREAD

**Issue by athanclark** [purescript/purescript-prelude#242]
Why isn't there a `Generic Unit rep` instance? Is it because there's no data constructors? If so, why would it not be technically trivial to generate a value of `Unit` given the fact that one exists? I'm not sure if I follow the technical reasoning why there isn't an instance, but I could see it because of how weird Unit is for purescript.

**Comment by garyb** [comment]
I don't know why there isn't an instance here - it could be because of the `Unit` representation, but I'm not sure if that matters so much with `-generic-rep`. Maybe someone else knows better?

I assume the instance would be
``` purescript
instance genericUnit ∷ Generic Unit (Constructor "Unit" NoArguments) where
  to _ = unit
  from _ = Constructor NoArguments
```

**Comment by JordanMartinez** [comment]
Should this issue be closed?

**Comment by hdgarrood** [comment]
Yes, I think so.
