### ISSUE TITLE
Add Data.Reflectable

### ISSUE THREAD

**Issue by purefunctor** [purescript/purescript-prelude#286]
The [type-level integers](https://github.com/purescript/purescript/pull/4207) PR for the compiler was recently merged and it introduces automatic solving for the `Reflectable` class which is defined as the following.
```hs
module Data.Reflectable where

class Reflectable :: forall k. k -> Type -> Constraint
class Reflectable v t | v -> t where
  reflectType :: forall proxy. proxy v -> t
```
I'll open a PR once ES modules land in this repository.

**Comment by JordanMartinez** [comment]
I believe the `proxy` type should be `Proxy`:
```diff
- reflectType :: forall proxy. proxy v -> t
+ reflectType :: Proxy v -> t
```
See #231 / #281

**Comment by JordanMartinez** [comment]
@PureFunctor The ES modules PR has been merged to this repo. Do you want to work on adding `Reflectable` now?

**Comment by purefunctor** [comment]
Yes, I'll do it in a few hours
