### ISSUE TITLE
Number is a poorly behaved Num, Ord

### ISSUE THREAD

**Issue by mkaemmerer** [purescript/purescript-prelude#30]
By using the native IEEE-754 floats for `Number`, we inherit a bunch of unfortunate quirks. `+Infinity`, `-Infinity`, `+0`, `-0`, and `NaN` break a several of the `Ord` and `Num` laws. Loss of precision breaks a few more.

I don't think Purescript should give up on `Number` entirely--it's clearly useful in terms of performance, and FFI, and generating readable compiled code. Still, I think its an egregious enough issue to warrant some sort of treatment.

Some potential approaches:
1. Leave `Number` as is, but document it as a non-conforming typeclass instance.
2. Do (1) and also move `Number` out of purescript-prelude, and into purescript-number.
3. Do (2) and also introduce a well-behaved numeric type to the prelude (e.g. `Rational`).
4. Do (1) and also introduce a well-behaved numeric type to the prelude. Encourage use of new type over `Number` for serious mathematics.

**Comment by paf31** [comment]
If we want to avoid orphan instances, the instances for Number have to be in Prelude unfortunately.

My vote would be for 4). I've started creating some new types like `Complex` now that we have a more sensibly-refined numeric hierarchy. I think rationals would make another good library to have.

**Comment by mkaemmerer** [comment]
I would have otherwise pushed for 3), but I hadn't considered the orphan instances problem. 4) is fine by me.

It may be a while before I can find the time, but if no one beats me to it, I'd be happy to contribute a `Rational` implementation.

**Comment by garyb** [comment]
`Int` has the same problems, but to an ever greater degree since it has an even smaller acceptable range of values. We did discuss these things elsewhere at some point, but I'm not sure where the issue is now - I thought the outcome of that was that we were going to document the non-law-abiding instances too, but I guess it got missed in the various updates we worked on for 0.7.
