### ISSUE TITLE
Add <**>

### ISSUE THREAD

**Issue by paf31** [purescript/purescript-prelude#32]
From https://github.com/purescript/purescript/issues/830 courtesy of @reuben364

**Comment by hdgarrood** [comment]
Maybe we should just close this? There doesn't seem to be enough interest to warrant it, I think. And it's easy enough to define locally to your project.

**Comment by texastoland** [comment]
There was a pretty intense discourse with yours truly. The only danger I see is subtlety noted by @paf31 in purescript/purescript-control#29. Also the operator doesn't evoke flippedness to me.

**Comment by LiamGoodacre** [comment]
Closing due to lack of interest.

**Comment by safareli** [comment]
reopened here https://github.com/purescript/purescript-prelude/issues/196
