### ISSUE TITLE
Add `Natural` type synonym?

### ISSUE THREAD

**Issue by garyb** [purescript/purescript-prelude#33]
For natural transformations:

``` purescript
type Natural f g = forall a. f a -> g a
```

Currently we have this in `Data.Coyoneda` but it's much more widely applicable and pretty generic, yet I'm not sure it's worth a module of its own as there aren't really any operations that go with it (I think?).

**Comment by paf31** [comment]
I guess the nice thing about type synonyms is that it really doesn't matter where they are defined, much like many of the `lens` libraries don't have to rely on `lens` for the `Lens` synonyms.

That said, there's no harm in putting it in prelude.

**Comment by ghost** [comment]
I have wanted this a few times and it's kind of awkward that its only defined in `purescript-free`. 

As for operations, I do have some stuff in [purescript-ends](https://github.com/freebroccolo/purescript-ends/blob/master/src/Data/Profunctor/End/Natural.purs) for the functor category, where transformations are ends of 𝒟 -hom profunctors wrt `f, g : 𝒞 → 𝒟`, i.e.,  `∫↓ x. 𝒟(f x, g x)`.

There are two types:

```
type NatPro hom f g = End (NatF hom f g)
type Nat f g = NatPro (->) f g
```

But this is packaging up natural transformations in a newtype which could be used for a category instance if we had polykinds. So it's not as convenient as the type synonym you suggest.
