### ISSUE TITLE
Why use Arrays for `cons`?

### ISSUE THREAD

**Issue by mjgpy3** [purescript/purescript-prelude#4]
What makes [using arrays for the underlying `cons` representation](https://github.com/purescript/purescript-prelude/blob/master/src/Prelude.purs#L130) worth the `O(n)` tradeoff?

I would kind of expected it too look more like the traditional `cons`:

``` javascript
var nil = function () {};

var cons = function (car) {
  return function (cdr) {
    return {
      car: car,
      cdr: cdr
    };
  };
};
```

Where you might instantiate a new list like:

``` javascript
cons(35)(cons(42)(nil))
```

I'm really liking purescript so far.
Peace.

**Comment by paf31** [comment]
You're right, it's a bad choice, and it's [being removed from Prelude in the next release](https://github.com/purescript/purescript/issues/1075) :)

**Comment by paf31** [comment]
Also, `purescript-lists` is probably what you're looking for.

**Comment by mjgpy3** [comment]
Awesome, thanks so much @paf31!
