### ISSUE TITLE
Deprecate (++)?

### ISSUE THREAD

**Issue by paf31** [purescript/purescript-prelude#40]
No need for both (++) and (<>).

**Comment by garyb** [comment]
But then we'll have an argument about which to keep :smile: I much prefer `(++)`, but know that's not a universal position. I could get used to it either way I guess.

Same goes for having both `return` and `pure`, I'd be all for ditching `return` (it has to be that way round considering this is PureScript :wink: also `return` has confusing connotations for some people, but then some other people will be expecting to use it, so you can't win).

**Comment by paf31** [comment]
I'd like to keep `<>` and `pure`. Ideally I'd like to have `Monoid < Semiring` and just use `+` :)

I prefer `<>` for no better reason than I find it more aesthetically pleasing, so I won't make a strong case for it.

**Comment by hdgarrood** [comment]
I agree, I'd rather remove one of them. I don't really mind which one - if we removed one of them, I'd be happy about it regardless of which one it was - but my vote would be to keep `(++)`.

**Comment by tfausak** [comment]
:+1: for removing `<>` and keeping `++`. 

Out of curiosity, what prevents the `Monoid < Semiring` setup?

**Comment by zudov** [comment]
I think it would be great to deprecate and remove both `(++)` and `return`.

**Comment by paf31** [comment]
If we're going to consider something which will break so much code, we should put together a list of things for `prelude-0.2`.

**Comment by zudov** [comment]
@paf31 We could just keep deprecating stuff and `grep -R Deprecated` would be giving us a nice list :laughing: 
When this list would become sufficiently long we release `0.2`

**Comment by cdepillabout** [comment]
> Out of curiosity, what prevents the Monoid < Semiring setup? 

@tfausak, If you have the Monoid < Semiring setup, then you need an instance of `Monoid` for `Int` and `Number`.

This doesn't really work since there are 4 commonly used `Monoid` instances for `Int`/`Number` :-\

> I'd like to keep <> and pure. I prefer <> for no better reason than I find it more aesthetically pleasing, so I won't make a strong case for it.

I agree with this.

**Comment by hdgarrood** [comment]
Is it definitely better to save up breaking changes and do them all in one go? You could also argue that the longer we leave it, the worse it will be to update everything when we do break it.

Also, please let's not worry too much about breaking things - one of my favourite things about PureScript is that it fixes a bunch of mistakes from Haskell's base libraries.

**Comment by garyb** [comment]
Yeah, I was going to propose this change as one of the things included in the breaking changes for the 0.8 prelude.

I'm back to preferring `(++)` again. My slightly flimsy reasoning is this: the operators based on `<>` are usually operating on some kind of functory type.

**Comment by hdgarrood** [comment]
I remain in favour of `(++)` because I think it suggests some kind of concatenation, at least more than `(<>)` does.

**Comment by paf31** [comment]
Unicode plus-in-a-circle? :smile:  /s

**Comment by sleexyz** [comment]
++, because semigroup's function is called `append`

**Comment by hdgarrood** [comment]
This has been resolved by the 0.8 updates, I think, as `++` was removed.
