### ISSUE TITLE
Semiring Maybe instance is badly behaved

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript-prelude#45]
`Semiring` has the following law:
- `zero * a = zero`

With the instance `(Semiring a) => Semiring (Maybe a)`, neither of these hold for `a = Nothing` - since `mul` is defined as `liftA2 mul`, `zero * Nothing = Nothing`, but `zero = Just zero`. Changing the definition of `zero` to be `Nothing` could fix this but might break other laws, I'm not sure. Maybe we should just remove this instance.

**Comment by garyb** [comment]
I think this issue is open on the wrong repo? :)

`Maybe` also has a non-law-abiding `MonadPlus` instance that we should remove while we're at it.

**Comment by hdgarrood** [comment]
Oh yes, of course. Oops.
