### ISSUE TITLE
Prelude v1.0.0 / for psc 0.8

### ISSUE THREAD

**Issue by garyb** [purescript/purescript-prelude#47]
@paf31 Instead of just threatening that I'm working on something I suppose I better explain what I'm doing before I get too far with it, in case we don't want to do this.

Now we have reliable re-exports, etc. we don't actually need a `Prelude` module to contain anything, and instead can just re-export everything like base/batteries/etc, so essentially I'm proposing that things get moved out into packages that they actually belong in. That also entails making some new packages:
- purescript-unit (this is purely the datatype, almost everything will end up depending on it transitively)
- purescript-newtype (so we can define `Newtype` instances for all the `Additive`, `Conj`, `Max` style newtypes we have lying around, frees us some from having to define every possible instance for these values as we can rely on the class to lift operations that aren't the "target" of the newtype)
- purescript-category (`Semigroupoid` and `Category` classes)
- purescript-equality (`Eq` class)
- purescript-booleans (`BooleanAlgebra` class, `Conj` and `Disj` monoid)
- purescript-bounded (`Bounded` class)
- purescript-num (the number hierarchy aside from `Semiring` which could live in `purescript-semirings`)

In addition to that, `Functor` would go to `purescript-functors`, the control classes would be moved to `purescript-control` and be defined in the appropriate modules, `Ord` would got to `purescript-orders`, and so on. Essentially the goal is to organise things in a way that is more natural, so that also means things like the monoids defined in `purescript-monoid` would be moved to their associated packages also, as mentioned with `Conj`/`Disj`, and we have already done with `First`/`Last`.

I'm working on all the packages at once to make sure this can work out without circular dependencies, etc. before I start submitting PRs everywhere and it gets hard to keep track of what's what, so once it's done I'll push the whole lot in one repo to github so we can review/discuss specifics if needs be. Or I can stop right now if we don't want to do this anyway... it does give us a few more dependencies to deal with, but I think the resulting organisation is more logical, and avoids some of the weirdness where `Data.Functor` doesn't define `Functor`, `purescript-semirings` doesn't contain `Semiring`, etc.

**Comment by hdgarrood** [comment]
Sounds sensible enough to me, and I can't think of any drawbacks. :+1: 

Do we have a `Newtype` class, or are we going to get one?

**Comment by garyb** [comment]
We had one and don't anymore, but we talked about reviving it in an issue on isos in `profunctor-lenses`, due to there being a ton of isos that could be covered by it.

**Comment by paf31** [comment]
Hmm, let me have a think about this. 

I'm definitely all for breaking up the modules, if only to make the output CommonJS modules smaller.

In terms of breaking up packages, I have to have a think about what it is Prelude is supposed to be. Does it serve the same function as something like `neon`, i.e. providing a collection of stuff you'll almost certainly need to do pretty much anything? Or should it not be special at all? I think we could go too far with breaking things up if we're not careful, and if we're cutting 1.0.0, this is the point of no return, so to speak. 

There is also the question of handling built-ins, like integer and boolean operators. That's a good job for a `Prelude`, I'd say. 

And having the compiler's built-in optimizations related to functions in one package (or more like two, I think, now, but whatever) is quite nice I think.

Do you know if the dependency order will work out okay?

Also, `newtype` is useful, but I worry that it might make things more difficult without fundeps. We can see anyway. My take on it is that `Iso` is what you want, and `Newtype` is something of an abuse of type classes.

**Comment by hdgarrood** [comment]
>  if we're cutting 1.0.0, this is the point of no return, so to speak.

Right; maybe we could try this, but stay on 0.x.y for now?

> `Newtype` is something of an abuse of type classes

This is more or less how I feel too, although perhaps this is a separate discussion.

**Comment by garyb** [comment]
I'm not sure `Prelude` is all that special anymore since we no longer auto-import it, so turning it into a "here's common things" module seems perfectly reasonable to me. Haskell's prelude is similar in some ways: it re-exports a lot of stuff (although, yeah, has its own definitions too).

The point about inlining native things is a pretty good one. I still hope that in the long run it's entirely unnecessary to have those special cases in the compiler at all, if we can handle them with rewrites somehow, perhaps. We're basically stuck with the prelude we have if this is something we definitely want to preserve - not being able to move `BooleanAlgebra` etc. out would make the dependency hierarchy problematic (so far I've not encountered any major problems, I'm pretty much done with the `Data` classes).

Yeah, lack of fundeps for `Newtype` was a concern for me too - I'm not suggesting we do away with the `runX` functions, just if we're going to provide a bunch of newtypes in the core libraries we may as well use that mechanism to give us better `Iso`s later?

Fair enough with the version, some of the other core libraries can almost certainly be bumped to `1.0.0` though.

**Comment by paf31** [comment]
My objection to `Newtype` shouldn't stop it from becoming a core library, especially if it's outside `Prelude` :smile: 

I think my opinion is that breaking out _some_ libraries is a good thing, but I probably wouldn't be quite as aggressive as your initial proposal. That said, I could make a case for not doing each one of the things you listed, but I do think _something_ should be changed.

I think it'd be quite nice (but not sure if possible) if we could somehow move things "downwards only", by adding new packages below `prelude`, having `prelude` reexport stuff, and not messing with other packages higher up. I feel like shunting things like `Conj` around is just asking for circular dependency issues, sadly.

**Comment by paf31** [comment]
First, let's identify the goals. I think one reasonable goal is to reduce the size of dependencies, by breaking things into smaller parts.

Any others?

**Comment by tfausak** [comment]
I'm happy to see both Neon and Batteries mentioned here :smile: I don't think I have any input for this thread, but please let me know if any of my tinkering can come in handy.

**Comment by garyb** [comment]
Closing this. I still intend to work on this alternative formulation, but not right now - got plenty of libraries to fix first!
