### ISSUE TITLE
Add `Void` type

### ISSUE THREAD

**Issue by garyb** [purescript/purescript-prelude#50]
We have at least two `Void`s floating around out there, and since we have `Unit` in the Prelude too it would seem to be sensible to add `Void`.

**Comment by paf31** [comment]
:+1: Agreed.

**Comment by michaelficarra** [comment]
Can you explain what `Void` is and how it differs from `Unit`?

**edit:** Let me guess: `data Void`? So zero inhabitants instead of one?

**Comment by paf31** [comment]
Yes, exactly.

**Comment by garyb** [comment]
#52
