### ISSUE TITLE
ModuloSemiring laws

### ISSUE THREAD

**Issue by jonsterling** [purescript/purescript-prelude#61]
I'm opening this ticket following a discussion with @paf31 on IRC. Here's what we've got:

``` purescript
-- | The `ModuloSemiring` class is for types that support addition,
-- | multiplication, division, and modulo (division remainder) operations.
-- |
-- | Instances must satisfy the following law in addition to the `Semiring`
-- | laws:
-- |
-- | - Remainder: ``a / b * b + (a `mod` b) = a``
class (Semiring a) <= ModuloSemiring a where
  div :: a -> a -> a
  mod :: a -> a -> a
```

This "law", however, is not valid unless we intend for the integers to fail to model the `ModuloSemiring` structure. In fact, the only instance of `ModuloSemiring` that actually follows this law presently is `Unit`. The problem is that nowhere has the behavior of division by zero been accounted for....
#### counterexample

Here's an example of where the law fails for `Number`. Fix `a : Number`, and let `b` be `0`. Then, we have the following chain of equations:
1. `(a / 0) * 0 + mod a 0`
2. `==> Infinity * 0 + mod a 0`
3. `==> 0 + 0`
4. `==> 0`

Therefore, `a` must be `0` for any `a`, which is clearly false.
#### discussion

what should we do? Unless I've made a mistake, this law is definitely wrong / not the intended definition of a `ModuloSemiring`. Can we fix it though? One option would be to say that it must only hold for non-zero `b`, but is that something we want to say in the type class itself? I'm curious what people think.

@garyb @paf31

**Comment by paf31** [comment]
`EuclideanDomain` seems like the right abstraction (although I'd also be fine with just removing `ModuloSemiring` honestly and putting `div` in `DivisionRing`). I would have `EuclideanDomain` and `DivisionRing` be unrelated in the hierarchy.

``` purescript
-- | Law: `a /= 0` and `b /= 0` implies `ab /= 0`
class Ring a <= IntegralDomain a

-- | Law: `a = b * dm.div + dm.mod` where `dm = divMod a b` and `degree dm.mod < degree b`
class IntegralDomain a <= EuclideanDomain a where
  degree :: a -> Int
  divMod :: a -> a -> { div :: a, mod :: a }
```

`EuclideanDomain` would be useful if we wanted to handle things like Gaussian integers or polynomial rings, but such things probably don't need to influence the `Prelude`.

**Comment by jonsterling** [comment]
@paf31 I think I like the idea of putting `div` in `DivisionRing` and separately, adding `EuclideanDomain`.

**Comment by paf31** [comment]
This is also the sort of thing we should figure out before 1.0, probably.

**Comment by paf31** [comment]
The `EuclideanDomain` approach would mean we'd have two unrelated `div` functions. I'm fine with that personally, but it might be a bit confusing for beginners.

_Edit_: beginners would probably not use `EuclideanDomain` anyway.

**Comment by jonsterling** [comment]
@paf31 My personal thinking is that `divMod` looks obscure enough that nobody will think to use it unless they "really" need it...

**Comment by garyb** [comment]
@jdegoes may have some thoughts on this too.

Removing `ModuloSemiring` is fine by me, in that we just made it up anyway, whereas the other divisions have some historical backing.

I wonder if it would be odd to beginners that they can't divide integers at all? Maybe less odd than allowing it though, actually :smile:

**Comment by garyb** [comment]
(I'm assuming `EuclideanDomain` would not be in the `Prelude`? How about `IntegralDomain`?)

**Comment by jonsterling** [comment]
@garyb not sure I follow about beginners not being able to divide integers, since isn't that what `divMod` would do? For what it's worth, I've found it confusing in the past to have to perform two separate operations to divide integers and then figure out the remainder.

**Comment by hdgarrood** [comment]
How would we implement `degree` for `EuclideanDomain Int`? Also, could this be a problem - from wikipedia:

> in general, a Euclidean domain will admit many different Euclidean functions.

(apparently a Euclidean function is another name for a degree function).

**Comment by paf31** [comment]
I'm suggesting that `div` would move into `DivisionRing`, and `EuclideanDomain` would be a completely different thing, a subclass of `Ring` and `IntegralDomain`, possibly in another module. The two notions of division would be unrelated.

**Comment by jdegoes** [comment]
This is a valid point, but note the laws for `DivisionRing` also fail for a similar reason.

I'd say that (a) there's clearly something between `Semiring` and `DivisionRing` (`EuclideanDomain`?) and that thing can have useful laws; and (2) laws for whatever that thing is called, as well as `DivisionRing`, probably need to explicitly exclude division by zero (someone should verify that's actually sufficient and that it's not necessary to support multiple "zeros" to define useful instances for non-numbers).

**Comment by hdgarrood** [comment]
I like being able to get both pieces of information from `divMod` at the same time. I also quite like having a `div` that works on integers, though; I find that I don't always want the `mod`. Is there any way to have a class with a member `div :: a -> a -> a` and sensible laws, such that, for `Int`, `div = _.div <<< divMod`?

Also I think we really ought to have some way of dividing integers in the Prelude. What reason is there not to include `EuclideanDomain` in the Prelude?

**Comment by paf31** [comment]
I don't think `EuclideanDomain` is between `Ring` and `DivisionRing` since `Number` is a `Ring` and a `DivisionRing`, but not a `EuclideanDomain` as far as I know. I think it is its own branch of the hierarchy with `Ring a <= IntegralDomain a <= EuclideanDomain a`.

_Edit_, or perhaps the reals are a euclidean domain, where the degree is just a constant? In which case inserting `EuclideanDomain` there possibly does make sense.

**Comment by paf31** [comment]
`Int` is still a `DivisionRing` like it always was.

**Comment by hdgarrood** [comment]
Ok then - if we can have both `EuclideanDomain Int` and `EuclideanDomain Number`, can we also have `div = _.div <<< divMod`, and `mod = _.mod <<< divMod`, which would then work on both?

**Comment by garyb** [comment]
> `Int` is still a `DivisionRing` like it always was.

Now I'm confused :smile:... `Int` isn't a `DivisionRing` now, and I don't see how it could be, since it doesn't meet the laws.

**Comment by paf31** [comment]
We could just think of `EuclideanDomain` as an improved `ModuloSemiring`. `Int` is a `EuclideanDomain` but not a `DivisionRing`, I think.

**Comment by garyb** [comment]
Ok, so since the 0.8 updates are stalled again by this, what's the plan?
- Is it just a case of dropping `ModuloSemiring` and having `EuclidianDomain`, `divMod`, etc. in a new library?
- Do we have anything useful to say about division by zero in the `DivisionRing` case? If not, do we need to do any of this, as it's undefined behaviour either way?

**Comment by jonsterling** [comment]
@gary 
1. Why not put `EuclidianDomain` in the prelude?
2. I think the `EuclidianDomain` thing that Phil brings up may actually be a side-issue (i.e. it only resolves the incorrect law in `ModuloSemiring` inasmuch as it introduces a new law which we shall hopefully write correctly this time). So, we could correct the `ModuloSemiring` law without doing any of this perhaps... Not sure whether we want to though.

I guess my main goal is to make sure that the documented laws/specifications are actually correct (i.e. so that I could write it as a QuickCheck property and have it validate the instances which we _claim_ are valid, which is more than we can currently do).

**Comment by garyb** [comment]
@jonsterling 

Re: 1. That's fine by me too, I just saw mention above that it might be something for a different library.

**Comment by garyb** [comment]
Here's my understanding of where we're at:

``` purescript
-- Commutative monoid under addition:
--   Associativity: `(a + b) + c = a + (b + c)`
--   Identity: `zero + a = a + zero = a`
--   Commutative: `a + b = b + a`
-- Monoid under multiplication:
--   Associativity: `(a * b) * c = a * (b * c)`
--   Identity: `one * a = a * one = a`
-- Multiplication distributes over addition:
--   Left distributivity: `a * (b + c) = (a * b) + (a * c)`
--   Right distributivity: `(a + b) * c = (a * c) + (b * c)`
-- Annihiliation: `zero * a = a * zero = zero`
class Semiring a where
  add  :: a -> a -> a
  zero :: a
  mul  :: a -> a -> a
  one  :: a

instance semiringInt :: Semiring Int
instance semiringNumber :: Semiring Number
instance semiringUnit :: Semiring Unit 

-- Additive inverse: `a - a = (zero - a) + a = zero`
class Semiring a <= Ring a where
  sub :: a -> a -> a

instance ringInt :: Ring Int
instance ringNumber :: Ring Number
instance ringUnit :: Ring Unit

-- Multiplicative inverse: `(one / x) * x = one` for `x /= 0`
class Ring a <= DivisionRing a where
  div :: a -> a -> a

instance euclidianDomainNumber :: DivisionRing Number
instance euclidianDomainUnit :: DivisionRing Unit

-- Commutative multiplication: `a * b = b * a`
-- 
-- aka Field, maybe we should just call it that? Num is more friendly, but given
-- the scarcity of instances I imagine it's rarely used as a constraint anyway,
-- and will never be inferred as such, as it's a "law class"
class DivisionRing a <= Num a 

instance numNumber :: Num Number
instance numUnit :: Num Unit
```

And then the discussion point: 

``` purescript
class Semiring a <= EuclidianDomain a where
  degree :: a -> Int
  divMod :: a -> { div :: a, mod :: a }

instance euclidianDomainInt :: EuclidianDomain Int
instance euclidianDomainNumber :: EuclidianDomain Number
instance euclidianDomainUnit :: EuclidianDomain Unit
```

Does it need to be a superclass of `DivisionRing` at all? Or merge with `DivisionRing` even? etc.

**Comment by garyb** [comment]
I snuck a "for `x /= 0`" into the laws of `DivisionRing` up there too ^ we could just say division by zero is undefined ¯_(ツ)_/¯. We'll get `Infinity` for `one / x`, and then `NaN` for `Infinity * zero` with `Number`, which kinda sucks, but I don't know how to efficiently prevent that from happening in the JS.

**Comment by paf31** [comment]
I think "for x /= 0" gets a bit interesting for constructive objects, like the constructive reals. For any `n` you might have, you can only semidecide `n == 0`, but _if_ you happen to have evidence already that `n /= 0`, then you should be able to use that to provide evidence that `m / n` is well-defined for all `m`, etc.

I'm talking beyond my ability level a bit here though. And getting off-topic, sorry.

**Comment by jonsterling** [comment]
I think it is still fine, since the meaning of implication in a constructive or intuitionistic setting does not require you to be able to decide the premise—it is a matter of assuming the premise.

**Comment by paf31** [comment]
Right :smile:  

The interesting one is `IntegralDomain`: `ab = 0 => a = 0 or b = 0`, which you might have to phrase constructively as `a /= 0 and b /= 0 => ab /= 0`.

**Comment by hdgarrood** [comment]
:+1: :+1: :+1: for renaming `Num` to `Field`. :)

**Comment by jonsterling** [comment]
@paf31 maybe... I guess it depends on whether your perspective is, "We want to classify the same objects that the classical version does" or "We want to classify the objects that the laws, when read constructively, generate". What Brouwer usually did is just divide these things up a bit more, and have one class for those objects that satisfy the strong law and another for those that satisfy the weak / classical law. Not necessarily saying we should do that here, but it's an idea.

**Comment by paf31** [comment]
What was the original `ModuloSemiring`/`DivisionRing` separation for? Is there an instance in between those two?

It gets a bit tricky because an `IntegralDomain` needs to be a commutative ring.

**Comment by garyb** [comment]
`Int` is `ModuloSemiring` but not `DivisionRing`.

**Comment by garyb** [comment]
Oh, as for _why_, I think it's just so there was a `(/)` that would work for `Int`.

**Comment by paf31** [comment]
One option could be to split the hierarchy with `CommutativeRing` and `IntegralDomain <= EuclideanDomain`, and have `(EuclideanDomain, CommutativeRing) <= Field` with `Field` also having inverses for non-zero elements. Then we'd have `Int` be a `CommutativeRing` and a `EuclideanDomain` but not a `Field`.

**Comment by paf31** [comment]
That doesn't leave a good place for `Quaternion` though. I suspect there might be a couple of parallel hierarchies here.

_Edit: `Quaternion` would be a `EuclideanDomain` but not a `CommutativeRing` in this setting, but we wouldn't capture the fact that it had multiplicative inverses. [This](http://math.stackexchange.com/questions/331020/do-people-ever-study-non-commutative-fields) suggests that it makes sense to keep `EuclideanDomain <= DivisionRing` and have `(CommutativeRing, DivisionRing) <= Field`. Then `Quaternion` would be a `DivisionRing` but not a `Field`.

**Comment by paf31** [comment]
Here's my suggestion:

``` purescript
-- (one, mul) is a monoid, (zero, add) is a comm. monoid, mul distributes over add
class Semiring a where
  one :: a
  mul :: a -> a -> a
  zero :: a
  add :: a -> a -> a

-- sub makes the additive bit of Semring into a group
class (Semiring a) <= Ring a where
  sub :: a -> a -> a

-- (one, mul) is a comm. monoid
class (Ring a) <= CommutativeRing a

-- the ring is an integral domain:
-- a /= 0 and b /=0 implies a *b /= 0
-- and has a multiplicative euclidean function:
-- a = (a `div` b) * b + (a `mod` b)
-- where
-- degree (a `mod` b) < degree b
-- degree a > 0 and degree a <= degree (a * b)
class (Ring a) <= EuclideanDomain a where
  degree :: a -> Int
  div :: a -> a -> a
  mod :: a -> a -> a

-- a field is a commutative ring with non-zero mult. inverses.
-- i.e. a `mod` b = 0 for all a, b
-- i.e. we can set degree b = 1 for all b
class (CommutativeRing a, EuclideanDomain a) <= Field a
```

**(Counter)examples**
- `Nat` is a `Semiring` but not a `Ring`
- The quaternions form a `Ring` but not a `CommutativeRing`
- `Z[X]`, the ring of polynomials with integer coefficients is a `CommutativeRing` but not a `EuclideanDomain` (consider the degrees of `x` and `2` and the expressions `div x 2` and `2 div x`, and get a contradiction)
- `Int` is a `CommutativeRing` and also a `EuclideanDomain` but not a `Field`
- `Number` is a `Field` (sort of)

**Comment by garyb** [comment]
Ok, got my head around all that. Sounds good to me :+1:
