### ISSUE TITLE
Break up BooleanAlgebra

### ISSUE THREAD

**Issue by paf31** [purescript/purescript-prelude#62]
cc @freebroccolo

We discussed modifying the `BooleanAlgebra` hierarchy on IRC.

I'd like to support some simple overloading of the boolean operations, while not splitting things into a full hierarchy of `Lattice`s, which I think would be fine in another library.

I propose:
- Split out `HeytingAlgebra`
- Make `Bounded` a subclass of `Ord`
- Copy the `Bounded` members into `HeytingAlgebra`

as follows:

``` purescript
-- See https://en.wikipedia.org/wiki/Heyting_algebra#Bounded_lattice_with_an_implication_operation
--
-- a ==> a = tr
-- a && (a ==> b) = a ==> b
-- b && (a ==> b) = b
-- a ==> (b && c) = (a ==>b) && (a ==> c)
--
-- plus the laws for a bounded lattice
--
-- plus `not a = a ==> fa`
class HeytingAlgebra h where
  tr :: h
  fa :: h
  implies :: h -> h -> h
  conj :: h -> h -> h
  disj :: h -> h -> h
  not :: h -> h

infix ==> as implies -- for the purposes of writing out the laws above

infix && as conj
infix || as disj

-- adds the law of the excluded middle
class (HeytingAlgebra b) <= BooleanAlgebra b
```

This allows us to interpret the operations of Boolean algebra in a variety of settings:
- `Boolean` itself
- Tuples
- Power sets of `Finite` types
- The interval `[0, 1]` with `min` and `max` operations (Heyting but not Boolean)
- Three-valued logic (Heyting but not Boolean)
- In general, we can create a `HeytingAlgebra` from any `Bounded` type with an order-reversing involution.

etc.

The tricky bit is that there is obviously an interaction with the `Ord` hierarchy here, but I'm trying to hide it in order to get something useable without refining the hierarchy too much, hence the formulation of `HeytingAlgebra` in terms of implication and conjugation, instead of the underlying order.

**Comment by garyb** [comment]
I'm not crazy about the names `tr` and `fa`, `fa` in particular is almost certainly going to be shadowed... but then I don't have any suggestions of alternatives either really.

Is there a counterexample of why we shouldn't use `Ord` or `Bounded` as a superclass here? We could use `top` and `bottom` for `tr` and `fa` perhaps then.

**Comment by paf31** [comment]
> Is there a counterexample of why we shouldn't use Ord or Bounded as a superclass here? 

There's no guarantee that you have a totally-ordered lattice, in general.

**Comment by garyb** [comment]
Ah right, and I assume we don't really want to go with `Poset <= Ord` after all?

**Comment by paf31** [comment]
I think that's going to be tricky, since we'd have to either change the type of `compare` or add another function to deal with incomparable values.

I don't think we need to be that fine-grained, honestly, at least not in Prelude.

**Comment by garyb** [comment]
`largest` and `smallest`? :wink:

**Comment by garyb** [comment]
:+1: for the proposal in general though. The implication operator is interesting, is that something that is generally useful, or is it mainly (for us anyway) for the laws?

**Comment by paf31** [comment]
I think we need names which suggest truth and falsehood, but I can't think of good ones.

I can see `implies` being potentially useful in some scenarios, but it's mainly there for the laws.

**Comment by ghost** [comment]
Also :+1: from me on this. In particular, I think introducing `HeytingAlgebra` but not much extra stuff is a good balance for the prelude.

As for naming, I agree with @garyb. Some potential alternatives:
- `ff`, `tt` (these names are often used in the type theory community but may be too short)
- `hbot`, `htop` (or `ibot`, `itop` for "intuitionistic")
- `falsum`, `verum` (at least I've seen the former used for `\bot` before)

As far as the implication operator goes, it feels a little weird coming at this from the boolean algebra side but in intuitionistic logic it is the more primitive notion and `not A` is defined as `A ==> fa`. Obviously with some sort of operational interpretation (e.g., lambda calculus) it feels more natural.

There is another way to look at the role of implication from a categorical rather than order theoretic perspective in terms of a special kind of symmetric monoidal category called a dialogue category. See [here](http://www.pps.univ-paris-diderot.fr/~mellies/papers/panorama.pdf) (page 79) where `⊗` corresponds to conjunction and `⊸` to implication.

The dialogue categories Melliès describes are like [*-autonomous](https://ncatlab.org/nlab/show/star-autonomous+category) categories where the negation is not required to be involutive up to isomorphism (i.e., from our perspective here it is not required to be boolean). See the "fourth definition" (page 81) and then the explanation (page 82) of the relationship between `⊸`/ `⊥` and `¬`/`⊗`.

A key issue which is sort of hidden here but would probably show up in some instances is the role that _variance_ plays, i.e., categorically `⊗` is a bifunctor but `⊸` is a profunctor. The definition section of [closed category](https://ncatlab.org/nlab/show/closed+category) has more about this.

**Comment by LiamGoodacre** [comment]
btw
`a && (a ==> b) = a ==> b`
is supposed to be
`a && (a ==> b) = a && b`

**Comment by garyb** [comment]
#64

**Comment by texastoland** [comment]
> I'd like to support some simple overloading of the boolean operations,

Would it be desirable to generalize `IfThenElse` in the compiler too? No use case just curious.

**Comment by garyb** [comment]
I think he was just referring to `not`, `(&&)` and `(||)` really. I'm not sure what we could do with `IfThenElse`, as `HeytingAlgebra` admits more values that `tt` and `ff` (that's actually why we're introducing it, the current `BooleanAlgebra`'s laws prevent 3 valued logic, etc.), so it's not a binary thing that is covered fully by `then` and `else` anymore.

**Comment by texastoland** [comment]
> I think he was just referring to `not`, `(&&)` and `(||)` really.

I realized that…

> HeytingAlgebra admits more values that `tt` and `ff`

But didn't know that! Skimming the wiki.

> the current BooleanAlgebra's laws prevent 3 valued logic,

So because `BooleanAlgebra` is effectively a synonym for `HeytingAlgebra` it's no longer restricted to a binary condition?

**Comment by garyb** [comment]
Not quite, types with an instance for `BooleanAlgebra` should satisfy "the law of the excluded middle":

`a || not a = tt`

So we can have a 3VL now that has an instance for `HeytingAlgebra` but not `BooleanAlgebra`, while every `BooleanAlgebra` is also a `HeytingAlgebra`.

The reason this law prevents 3VLs etc. is they usually define a complement something like this:

``` purescript
not T = F
not U = U
not F = T
```

So `U || not U = U`, whereas the law says it must equal `T`.

**Comment by texastoland** [comment]
Thanks makes sense! Could `IfThenElse` hypothetically check for `BooleanAlgebra` instead of primitive? Again I have no idea how it'd be useful.

**Comment by garyb** [comment]
I think we'd need to impose an `Eq` constraint on `HeytingAlgebra` (or `BooleanAlgebra`) for that to work, as we'd want to check `x == tt`, but yeah in theory that could work. It's true of any of the functions that we currently use the concrete `Boolean` type in actually.

@paf31 even if we don't generalise `IfThenElse`, think it's worth adding `Eq`?

**Comment by michaelficarra** [comment]
@garyb The `Eq` constraint wouldn't need to be on `HeytingAlgebra` or `BooleanAlgebra` itself, just as a constraint on the `IfThenElse`, right?

**Comment by garyb** [comment]
Yeah, that's true enough.

**Comment by texastoland** [comment]
For background the questions has been floating around my head since an [old post](http://tom.lokhorst.eu/2009/09/deeply-embedded-dsls) about `AwesomePrelude`. He defined a `Boolean` type class with an `If` type expression instead of ternary.

**Comment by paf31** [comment]
Please let's not overload `if then else` at the moment. What would we add `Eq` to?

**Comment by texastoland** [comment]
Wasn't a question of whether (I don't have a use case), just why not (I couldn't find the reference in Haskell either)?

**Comment by paf31** [comment]
`if then else` is the fold for the `Boolean` type, since it has exactly two values. You could overload it, but you'd be using `HeytingAlgebra` artificially - you just want a decidable check for whether a value equals some special value in the type which you've determined to be truthy.

Let me turn the question around and say - what's the compelling use case for overloading?

**Comment by texastoland** [comment]
> what's the compelling use case for overloading?

Boolean not Heyting. None at all just a question.

**Comment by paf31** [comment]
Well, my use case for `HeytingAlgebra`, like with most of these things, is to enable some basic form of abstract interpretation for the operations of the class, so that we can talk abstractly about things like implication. `if then else` doesn't really fit into that use case IMO, but perhaps there is another overloading which makes sense one day. I'm reluctant to add overloading, since it'll be difficult to take it out later. There is another thread about this somewhere, I think.

**Comment by AppShipIt** [comment]
> There is another thread about this somewhere, I think.

Not in this repo. Didn't raise an issue because it's not terribly important.
