### ISSUE TITLE
Array Semigroup instance should check length

### ISSUE THREAD

**Issue by natefaubion** [purescript/purescript-prelude#63]
If either of the arrays are 0-length, then we should return the other as is instead of unnecessarily creating a copy.

**Comment by hdgarrood** [comment]
Do we know if JS VMs do this already? (And why not, if not?)

Even if they don't, I think doing this could have a cost for `foldMap` on large structures. I'd like to see benchmarks first.

**Comment by garyb** [comment]
They don't do so, as `concat` always shallow-copies arrays in JS by design.

Can you explain a bit more about your concern with `foldMap`? I'm not sure what you're thinking there.
