### ISSUE TITLE
Bad escape in Show

### ISSUE THREAD

**Issue by nwolverson** [purescript/purescript-prelude#65]
Sorry if this is the wrong place - but I think it's maybe multiple issues.

I get the following error from `psc-bundle` 0.8.3 (only on Windows!):

```
Error in module Prelude (Foreign):

  The module could not be parsed:
  lexical error @ line 216 and column 14
```

This points at: https://github.com/purescript/purescript-prelude/blob/4c97cecbf041f27b83f7ae9d39fc2d9b24a097f4/src/Prelude.js#L216

The same line is present in the 1.0-rc modularised version. As far as I can see (eg [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_types#Using_special_characters_in_strings)) `\a` isn't actually a JavaScript string escape sequence, which is why I think it's an issue here - can we remove it? On the other hand the behaviour for an unknown escape should be to pass it through (`\a` means precisely `a`), which would be an issue for language-javascript, probably post https://github.com/purescript/purescript/issues/1966.

**Comment by joelgrus** [comment]
I am having the same issue on Ubuntu, as linked above.

**Comment by garyb** [comment]
Just to check, you're getting this from the `v0.1.4` library release when compiled with psc 0.8.3?

**Comment by garyb** [comment]
@michaelficarra can you comment on the escape sequence issue at all here? Is `\a` redundant, or is there something we should be handling?

**Comment by nwolverson** [comment]
I am, a fresh install from npm of 0.8.3 and using 0.1.4. (Though seems clear the same would hold of 1.0.0-rc2).

As noted on the linked issue psc doesn't compile `"\a"` to `"\a"` in PureScript source.

**Comment by garyb** [comment]
Ok, yep, I see it too. Thanks.

I wonder why it was fine in 0.8.2...

**Comment by alogic0** [comment]
`language-javascript` can't parse this file until comment strings where is `"\a"`:  

```
GHCi, version 7.10.2: http://www.haskell.org/ghc/  :? for help
Prelude> :m +Language.JavaScript.Parser
Prelude Language.JavaScript.Parser> parseFile "purescript-prelude/src/Data/Show.js"   
*** Exception: "lexical error @ line 18 and column 14"
```

**Comment by michaelficarra** [comment]
@garyb That was my bad. I will remove it.
