### ISSUE TITLE
A proposal for generalized `abs`

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript-prelude#66]
I think it would be nice to get some concept of `abs` which works for not only `Int` and `Number`, but also more exotic numeric types, like `Rational`, `Complex`, and even `Quaternion` (when we eventually implement it ;).

Given that we (well, I) want this to work for numeric types which don't have total orders (such as `Complex`), I thought a good starting point would be to take laws from https://en.wikipedia.org/wiki/Absolute_value but remove all those to do with ordering, so:

``` purescript
class Semiring a <= Absolute a where
  abs :: a -> a
```

Laws:
- Positive-definiteness: `abs x == zero iff x == zero`
- Multiplicativeness: `abs (x * y) == abs x * abs y`
- Idempotence: `abs (abs x) == abs x`

We could add more laws by making the constraint a bit stronger, to `Ring` if we want those that mention subtraction, or maybe even `EuclideanRing` if we want those that mention division. But the above seems a good starting point, I think.

**Comment by hdgarrood** [comment]
Oh, also worth considering:

``` purescript
class ??? a where
  signum :: a -> a
```

with the law that `abs x * signum x == x`. I'm not able to come up with any examples of a type that has a sensible `abs` but no sensible `signum`, so maybe these two should go in the same class.

**Comment by garyb** [comment]
It seems like there's a generalisation already: https://en.wikipedia.org/wiki/Absolute_value_%28algebra%29

Going by

> a function which measures the "size" of elements in a field or integral domain

In our hierarchy that would suggest the `EuclideanRing` superclass I guess.

**Comment by hdgarrood** [comment]
That looks good, except that I think I'd rather have `abs :: Absolute a => a -> a` rather than `abs :: Absolute a => a -> Number`. I've definitely wanted `abs :: Int -> Int` before, for example, and if I were using `Rational`, I expect `abs :: Rational -> Rational` would be more useful than `abs :: Rational -> Number` too.

**Comment by sharkdp** [comment]
:+1: for some version of this

> That looks good, except that I think I'd rather have abs :: Absolute a => a -> a rather than abs :: Absolute a => a -> Number. I've definitely wanted abs :: Int -> Int before, for example, and if I were using Rational, I expect abs :: Rational -> Rational would be more useful than abs :: Rational -> Number too.

True. On the other hand, for `Complex` I would expect `abs :: Complex -> Number` to be more helpful (or whatever the base type of `Complex` is).

**Comment by hdgarrood** [comment]
Yes, although unfortunately I don't see a good way of coming up with sensible laws for an `abs` which can do that, unless we also introduce some idea of scalar multiplication to the class. At that point, I think we'd be dealing with vector spaces, which is perhaps a bit much for the prelude's numeric hierarchy. For that, I think I'd rather have something like a `class (Field f, Semiring v) <= VectorSpace v f` in a separate library, at least for a some trial period to see how well it works.

**Comment by sharkdp** [comment]
> Yes, although unfortunately I don't see a good way of coming up with sensible laws for an abs which can do that, unless we also introduce some idea of scalar multiplication to the class.

The laws in [the Wikipedia article](https://en.wikipedia.org/wiki/Absolute_value_%28algebra%29) don't require scalar multiplication:

``` purs
class CommutativeRing a <= Absolute a where
  abs :: a -> Number

-- Laws:
abs x >= 0.0
abs x == 0.0  iff  x == zero
abs (x * y) == abs x * abs y
abs (x + y) <= abs x + abs y
```

Multiplication and addition are either performed within the `CommutativeRing` (left-hand side in the last two laws) or between two `Number`s (right-hand side).

I'm not sure about the `CommutativeRing` constraint.. maybe this could even be weakened.

On the other hand, coming back to your previous point, I also agree that `abs :: Int -> Int` would be more useful than `abs :: Int -> Number`.

Edit: [Gist with some instances](https://gist.github.com/sharkdp/cef1f5e2eddd1125176d08daa03ef45a)

**Comment by hdgarrood** [comment]
Oh of course, yes. Although if we want to handle cases where we have some result type other than `Number`, maybe something like:

``` purescript
class (CommutativeRing a, Ord r, Semiring r) <= Absolute a r where
  abs :: a -> r
```

with the laws you listed (except replace `0.0` with `zero`). If we have `Ring a` it probably makes sense to add an evenness law too: `abs (negate x) == abs x`.

Perhaps I'm overthinking this, though. Maybe it will help to list the functions/concepts which we might want:
- For any ordered ring R, I think we want an `abs :: R -> R` which is just `\x -> if x > zero then x else negate x`
- For `Complex`, and `Quaternion`, we want a `modulus` function which gives you a `Number` (or whatever the underlying type is).
- For vector spaces of a set V over a field F, we want a `norm :: V -> F`. If `norm` is going into a type class, that type class will also need some concept of scalar multiplication, I think.

I think that's everything.

I personally have never wanted to write functions that deal with or abstract over more than one of the above three concepts at once. Given this (assuming it isn't just me), perhaps it doesn't really make sense to try to come up with a unifying generalisation. So maybe we should just define `abs :: (Ord a, Ring a) => a -> a` in `Data.Ring` and leave the other concepts to be dealt with by other libraries.

**Comment by garyb** [comment]
I don't have strong feeling about any of this, so just thought I'd comment on one aspect of `Absolute a r`: it will probably suffer the same way the MTL stuff does, in that it will often require some type hinting as we can't say `| a -> r` (yet).

**Comment by hdgarrood** [comment]
Oh, yeah, of course. I think that strengthens my position, then, that the option which seems most attractive to me now is just to add a `Data.Ring.abs :: (Ord a, Ring a) => a -> a` and leave anything else to other libraries.

**Comment by garyb** [comment]
I think that's a fair position to take for the `Prelude`. Similar reasoning (handling the common cases) is what led us to `HeytingAlgebra` rather than having an integrated poset/ord/lattice/boolean algebra hierarchy.

**Comment by sharkdp** [comment]
> So maybe we should just define abs :: (Ord a, Ring a) => a -> a in Data.Ring and leave the other concepts to be dealt with by other libraries.

:+1:
