### ISSUE TITLE
Show Number can produce invalid Number literals

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript-prelude#71]
For integers outside the `Int` range, you might get an `Int` literal instead of a `Number` (note that `Number` literals are required to either contain a decimal point or an exponent).

For example:

```
> show (1e10 :: Number)
10000000000
> :t 10000000000
[Integer value is out of range...]
```

I suggest that instead of the bitwise-or-with 0 check, we check that the produced string either contains a decimal point or an 'e' or 'E', and if not, append ".0".

**Comment by garyb** [comment]
I was going to say I thought we already handled this, but I see now the current trick is not sufficiently tricky to work properly. :+1: for fixing.
