### ISSUE TITLE
Add (>>)

### ISSUE THREAD

**Issue by lexi-lambda** [purescript/purescript-prelude#74]
I noticed that the `>>` operator is not included in `Control.Bind`. One guess as to why would be that PureScript does not currently support default typeclass method implementations, and `>>` is a member of the `Monad` class in Haskell, but I think it would be just fine to introduce it as a separate function to start and move it into the typeclass once default methods are supported.

I’d be happy to write a PR to introduce this, but I was wondering if there was any ideological reason for leaving it out.

**Comment by paf31** [comment]
The equivalent operator is `*>` in `Control.Apply`. Note you only need `Apply`, not `Bind`.

**Comment by lexi-lambda** [comment]
Ah! That makes sense in retrospect—I guess I’ve been conditioned to use the monad-specific versions in Haskell due to the historical idioms there. Thanks for your very quick response. :)
