### ISSUE TITLE
Creating an npm package

### ISSUE THREAD

**Issue by wegry** [purescript/purescript-prelude#81]
Would you folks be willing to create an npm package containing the prelude?

**Comment by hdgarrood** [comment]
Maybe; what would you want it for? Note that npm isn't a good fit for managing purescript dependencies in purescript projects, at least not right now: http://harry.garrood.me/blog/purescript-why-bower/

**Comment by wegry** [comment]
Thanks for the quick response. I was wondering if it would be possible to remove the bower dependency—which your blog post touches on. Looks like I’m using both npm and bower for now.
