### ISSUE TITLE
Functor function

### ISSUE THREAD

**Issue by joneshf** [purescript/purescript-prelude#82]
I don't have a good name for this—nor do I care what the name is. Been calling it `flip'` in my head, since it generalizes `flip`. It's been lingering in `purescript-lens` for too long, and doesn't make sense there anymore. Should it be moved here?

``` purescript
infixl 1 flip' as ??

flip' :: forall f a b. (Functor f) => f (a -> b) -> a -> f b
flip' ff x = map (\f -> f x) ff
```

Some example uses:

``` purescript
longEnough :: String -> Bool
hasSymbol :: String -> Bool
hasDigit :: String -> Bool
password :: String

validate :: String -> List Bool
validate = flip' [longEnough, hasSymbol, hasDigit]
```

``` purescript
flip' (-) 3 4 -- => 1
```

``` purescript
foo <*> pure x == foo ?? x
```

**Comment by paf31** [comment]
Sounds good to me, although I might change the symbol.

**Comment by joneshf** [comment]
Sounds good, I'll open a PR.
