### ISSUE TITLE
Lattice laws

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript-prelude#9]
Based on https://en.wikipedia.org/wiki/Lattice_(order) should `Lattice` have the following additional laws?
- Supremum:
  - `x || y >= x`
  - `x || y >= y`
- Infimum:
  - `x && y <= x`
  - `x && y <= y`

We could potentially go even further and require that `x || y` is the least upper bound of `{x, y}`, and similar for `&&`.

**Comment by paf31** [comment]
Our lattices are complete lattices, yes? In which case, I think both sets of laws make sense to add.

**Comment by garyb** [comment]
Do those not follow from the laws we already state?

**Comment by hdgarrood** [comment]
I don't think so - you could have:

```
instance latticeInt :: Lattice Int where
  sup = const (const 0)
  inf = const (const 0)
```

I think this instance satisfies all the current laws, but not the two above ones.

**Comment by paf31** [comment]
Yes, there are no laws which mention both (`compare` or `<`) and (`sup` or `inf`).

**Comment by garyb** [comment]
Ah yeah, of course.
