### ISSUE TITLE
Why does mod return 0.0 for Numbers?

### ISSUE THREAD

**Issue by Risto-Stevcev** [purescript/purescript-prelude#97]
https://github.com/purescript/purescript-prelude/blob/403334821953d50fb6eae4b40efd1e542e3e47de/src/Data/EuclideanRing.purs#L36

**Comment by paf31** [comment]
This is required by the [laws for `Field`](https://github.com/purescript/purescript-prelude/blob/403334821953d50fb6eae4b40efd1e542e3e47de/src/Data/Field.purs#L20), since every non-zero `Number` has a multiplicative inverse.
