### ISSUE TITLE
Consider renaming # to |>

### ISSUE THREAD

**Issue by Pauan** [purescript/purescript-prelude#98]
I think the vast majority of the syntax in PureScript is great, but I feel like the [`#` syntax](https://pursuit.purescript.org/packages/purescript-prelude/1.1.0/docs/Data.Function#v:%28#%29) is ugly.

I think this is one of the rare examples where F# has nicer syntax than PureScript: they use `|>` instead.

Compare:

```
products # filter isInStock # groupBy productCategory # length
```

```
products |> filter isInStock |> groupBy productCategory |> length
```

Yes, it's an extra character to type, but I think it looks much nicer.

It reminds me of the Unix `|` syntax for piping, and it also visually suggests that we are feeding the output from the left side of `|>` into a function on the right side of `|>`

---

P.S. I think `$` should **not** be changed to `<|`, this is only about changing `#`

P.P.S. I also thought about renaming `#` to `>>` and renaming `$` to `<<` for consistency, but I think that would cause confusion with `>>>` and `<<<`

**Comment by natefaubion** [comment]
It's pretty trivial (and encouraged) to have your own `Prelude` for stuff like this. Since it would just be a different alias for `applyFlipped` you'd still get optimizations. I know `#` is a bit arbitrary, but I'd be surprised if it changed (note there's also `<#>` to go along with `<$>`).

**Comment by Pauan** [comment]
@natefaubion You're right, `<#>` complicates things a lot.

How would somebody go about creating a custom Prelude? I guess they'd use something like this:

```
module Pauan.Prelude (module Prelude, (|>)) where

infixl 1 applyFlipped as |>
```

Then they would have to publish it to Bower/Pursuit, and then they could import it and use it:

```
import Pauan.Prelude
```

Am I understanding this correctly?

**Comment by garyb** [comment]
Yep, pretty much. Although the publishing it part is optional, it depends if you want to use it frequently - [we have a custom prelude](https://github.com/slamdata/slamdata/blob/master/src/SlamData/Prelude.purs) we use just in the main SlamData project, but don't bother with it in the other SlamData libraries, for example.

**Comment by Pauan** [comment]
@garyb Thanks, that helps out a lot.

I think it would be nice if `#` were improved in `purescript-prelude`, but it's probably too big of a breaking change for too small of a gain.
